[tool.poetry]
name = "megatron-deepfake"
version = "0.1.0"
description = "Deep fake detector using Transformers"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tqdm = "^4.66.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
